config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  root to: 'pages#home'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  namespace :admin do
    root to: 'products#index'
    resources :products, only: [:index, :new, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :new, :create, :edit, :update, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :product_categories
  has_many :products, through: :product_categories
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :product_categories, dependent: :destroy
  has_many :categories, through: :product_categories
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController

  before_action :authenticate_admin!

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was added!"
      redirect_to admin_categories_path
    else
      flash[:notice] = "Category cannot be blank!"
      render 'admin/product/new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category updated!"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category = Category.destroy(params[:id])
    flash[:notice] = "Category removed!"
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController

  before_action :authenticate_admin!

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      @category_array = params.dig(:product, :category_ids)
      @category_array.each do |cat|
        @category = Category.find(cat)
        @product.categories << @category
      end
      flash[:notice] = "Product added!"
      redirect_to admin_products_path
    else
      flash[:notice] = "Product cannot be blank!"
      render 'admin/product/new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      @product.product_categories.destroy_all
      @category_array = params.dig(:product, :category_ids)
      @category_array.each do |cat|
        @category = Category.find(cat)
        @product.categories << @category
      end
      flash[:notice] = "product updated!"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.destroy(params[:id])
    flash[:notice] = "product removed!"
    redirect_to admin_products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
    @products = @category.products.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, raise: false, only: [ :home, :products ]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def index
        @products = Product.all
    end

    def show
       @product = Product.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_admin_category.html.erb
<tr>
  <td><%= admin_category.name %></td>
  <td> <%= link_to "Edit", edit_admin_category_path(admin_category) %> </td>
  <td> <%= link_to "Delete", admin_category_path(admin_category), method: :delete %> </td>
</tr>

app/views/admin/categories/edit.html.erb
<div class="jumbotron">
  <h1>Edit Categories</h1>
</div>
  <div class="container">
    <%= simple_form_for [:admin, @category ], class: "form-horizontal" do |f| %>
      <%= f.input :name %>
      <%= f.button :submit %>
    <% end %>
    <%= link_to "Back to Category List", admin_categories_path %>
  </div>

app/views/admin/categories/index.html.erb
<div class="jumbotron">
  <h1>Admin | Categories</h1>
</div>
  <div class="container">
    <div class="row">
      <%= link_to "Add Category", new_admin_category_path %>
      <table class="col-12">
        <thead>
          <th>Name</th>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <%= render partial: "admin_category", collection: @categories %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/admin/categories/new.html.erb
<div class="jumbotron">
  <h1>New Categories</h1>
</div>
  <div class="container">
    <%= simple_form_for [:admin, @category ], class: "form-horizontal" do |f| %>
      <%= f.input :name %>
      <%= f.button :submit %>
    <% end %>
    <%= link_to "Back to Category List", admin_categories_path %>
  </div>

app/views/admin/products/_admin_product.html.erb
<tr>
  <td><%= admin_product.name %></td>
  <td><%= admin_product.description %></td>
  <td><%= admin_product.price %></td>
  <td> <%= link_to "Edit", edit_admin_product_path(admin_product) %> </td>
  <td> <%= link_to "Delete", admin_product_path(admin_product), method: :delete %> </td>
</tr>

app/views/admin/products/edit.html.erb
<div class="jumbotron">
  <h1>Edit Products</h1>
</div>
  <div class="container">
    <%= simple_form_for [:admin, @product ], class: "form-horizontal" do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>

      <%= f.association :categories, collection: Category.all, as: :check_boxes, include_hidden: false%>

      <%= f.button :submit %>
    <% end %>
    <%= link_to "Back to product List", admin_products_path %>
  </div>

app/views/admin/products/index.html.erb
<div class="jumbotron">
  <h1>Admin | Products</h1>
</div>
  <div class="container">
    <div class="row">
      <%= link_to "Add Category", new_admin_product_path %>
      <table class="col-12">
        <thead>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
        </thead>
        <tbody>
          <% @products.each do |product| %>
          <%= render partial: "admin_product", collection: @products %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

app/views/admin/products/new.html.erb
<div class="jumbotron">
  <h1>New Products</h1>
</div>
  <div class="container">
    <%= simple_form_for [:admin, @product ], class: "form-horizontal" do |f| %>
      <%= f.input :name %>
      <%= f.input :description %>
      <%= f.input :price %>

      <%= f.association :categories, collection: Category.all, as: :check_boxes, include_hidden: false%>

      <%= f.button :submit %>
    <% end %>
    <%= link_to "Back to product List", admin_products_path %>
  </div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<div class="container">
    <%= render partial: "shared/card", collection: @products %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ECommerceStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <div class="main-logo">
      <%= link_to :root do %>
        <%= image_tag "logo" %>
      <% end %>
    </div>

    <%= render 'shared/pages_navbar' %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-container">
  <div class="container">
    <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.picsum.photos/id/1059/7360/4912.jpg?hmac=vVWk1qyiXN_VgPhpNqFm3yl2HUPW6fHqYOjTHYO2bHQ);">
      <!-- <div class="container"> -->
        <!-- <h1>Le Wagon brings <strong>tech skills</strong> to <strong>creative people</strong>!</h1>
        <p>Change your life and learn to code at one of our campuses around the world.</p> -->
      <!-- </div> -->
    </div>
    <div class="nav-card">
      <%= link_to products_path do %>
      <div class="home-card" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.picsum.photos/id/856/4500/3112.jpg?hmac=VFr8pGzI1NbVoTha8W_Mw11pqEvh8OW5QXOAcZbGrBY);">
        <div class="card-text">
          <h1><em>BROWSE</em></h1>
          <P>See all products</P>
        </div>
      </div>
      <% end %>
      <div class="home-card" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://i.picsum.photos/id/669/4869/3456.jpg?hmac=g-4rQWsPdHoLi5g6ahHlvjKubSQzR-D9m7-WtblbmyM);">
        <div class="card-text">
          <h1><em>POPULAR</em></h1>
          <P>Shop most loved</P>
        </div>
      </div>
    </div>
    <hr>
    <div class="d-flex justify-content-center">
      <%= render "shared/carousel" %>
      <div class="vl"></div>
      <div class="form-container">
        <div class="form-logo d-flex">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing, elit. Maiores laudantium minus omnis a molestiae non dicta nisi culpa nesciunt ipsum aut, ratione qui quaerat laborum nulla voluptate quia reiciendis dolore!</p>
          <%= image_tag "logo" %>
        </div>
        <form>
          <div class="form-row">
            <div class="form-group email-form d-flex">
              <label for="inputEmail4"></label>
              <input type="email" class="form-control" id="inputEmail4" placeholder="email@example.com">
              <button type="submit" class="btn btn-email">Sign up</button>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <%= render partial: "shared/card", collection: @products %>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="show-box">
    <div class="show-pic">
      <%= image_tag "vans", alt: "Vans jacket"%>
    </div>
    <div class="show-info">
      <h1><%= @product.name %></h1>
      <h2>£<%= @product.price %></h2>
    </div>
  </div>
  <div class="show-description">
    <p><%=  @product.description %></p>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="card-container">
  <% @products.each do |product| %>
    <%= link_to(product_path(product.id)) do %>
    <div class="index-card">
      <%= image_tag "vans", alt: "Vans jacket"%>
      <div class="card-info">
        <h3><%= product.name %></h3>
        <p>£<%= product.price %></p>
      </div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/shared/_carousel.html.erb
<div class="carousel-container">
  <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://picsum.photos/id/1012/3973/2639" class="d-block w-100" alt="First slide">
      </div>
      <div class="carousel-item">
        <img src="https://picsum.photos/id/157/6211/4862" class="d-block w-100" alt="Second slide">
      </div>
      <div class="carousel-item">
        <img src="https://picsum.photos/id/2/5616/3744" class="d-block w-100" alt="Third slide">
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class=info-container>
    <div class="footer-info">
      <ul>
        <h3>MORE INFO</h3>
        <li>Contact Us</li>
        <li>Refunds & Exchanges Policy</li>
        <li>FAQ</li>
        <li>Terms & Conditions</li>
        <li>Privacy Policy</li>
        <li>Order Status</li>
      </ul>
    </div>
    <div class="link-container">
      <h3>FOLLOW US</h3>
        <div class="footer-links">
          <a href="#"><i class="fab fa-github"></i></a>
          <a href="#"><i class="fab fa-instagram"></i></a>
          <a href="#"><i class="fab fa-facebook"></i></a>
          <a href="#"><i class="fab fa-twitter"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
    </div>
  </div>
  <hr>
  <div class="footer-copyright">
    This website was made with <i class="fas fa-heart"></i> by 'el Tefe' 2021
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div>
  <%= link_to "#", class: "navbar-brand" do %>
    <p class="nav-info"><em>Free UK delivery on all orders over £100</em></p>
    <% end %>

    <div class="search-right">
    <form class="form-inline search-pages my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
    </form>
    </div>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="icon-container">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <%= link_to '#', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false do %>
            <i class="fas fa-user"></i>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Home", root_path, class: "dropdown-item" %>
            <%= link_to "Edit Account", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_session_path do %>
            <i class="far fa-user"></i>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="wishlist">
    <i class="far fa-heart"></i>
  </div>
  <div class="cart">
    <i class="fas fa-shopping-cart"></i>
  </div>
  </div>
</div>

app/views/shared/_pages_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-transparent">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <!-- <a class="navbar-brand" href="#">Navbar</a> -->

  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
    <div class="middle-links">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link"><%= link_to "Home", root_path %></a>
      </li>
      <% Category.all.each do |category| %>
      <li class="nav-item">
        <a class="nav-link"><%= link_to category.name.capitalize, category_path(category) %></a>
      </li>
      <% end %>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Accessories</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Sale</a>
      </li>
    </ul>
    <% if admin_signed_in? %>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Categories", admin_categories_path %></a>
      </li>
      <li class="nav-item">
        <a class="nav-link"><%= link_to "Products", admin_products_path %></a>
      </li>
    </ul>
    <% end %>
    </div>
  </div>
</nav>